In [2]:
import gymnasium as gym
import numpy as np

envs = gym.make_vec('CartPole-v1', num_envs= 1000)
envs.single_action_space.n
np.random.choice(2)

0

In [3]:
from torch import Tensor
import torch
import numpy as np

test = np.random.choice([True,False],size=100)
test2 = Tensor(np.arange(100).reshape(10,10))
torch.max(test2, 1)[0]

tensor([ 9., 19., 29., 39., 49., 59., 69., 79., 89., 99.])

In [4]:
loss = torch.nn.MSELoss()
y, q = Tensor([1,2,3]),Tensor([2,3,4])
loss(y,q)

tensor(1.)

In [5]:
m = torch.nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)
output

tensor([[0.0763, 0.0962, 0.8275],
        [0.3690, 0.3508, 0.2802]])

In [7]:
z = Tensor([3,5,6])
for yi, qi, zi in zip(y,q,z):
    print(yi,qi, zi)

tensor(1.) tensor(2.) tensor(3.)
tensor(2.) tensor(3.) tensor(5.)
tensor(3.) tensor(4.) tensor(6.)


In [8]:
import gymnasium as gym

help(gym.make_vec)

Help on function make_vec in module gymnasium.envs.registration:

make_vec(id: 'str | EnvSpec', num_envs: 'int' = 1, vectorization_mode: 'VectorizeMode | str | None' = None, vector_kwargs: 'dict[str, Any] | None' = None, wrappers: 'Sequence[Callable[[Env], Wrapper]] | None' = None, **kwargs) -> 'gym.vector.VectorEnv'
    Create a vector environment according to the given ID.
    
    To find all available environments use :func:`gymnasium.pprint_registry` or ``gymnasium.registry.keys()`` for all valid ids.
    We refer to the Vector environment as the vectorizor while the environment being vectorized is the base or vectorized environment (``vectorizor(vectorized env)``).
    
    Args:
        id: Name of the environment. Optionally, a module to import can be included, e.g. 'module:Env-v0'
        num_envs: Number of environments to create
        vectorization_mode: The vectorization method used, defaults to ``None`` such that if env id' spec has a ``vector_entry_point`` (not ``None``

In [29]:
t = torch.tensor([[1, 2], [3, 4]])
action = [0,1]
action_index = torch.tensor([[a] for a in action])
torch.gather(t, 1, action_index)

tensor([[1],
        [4]])